let mapleader=" "
noremap j h
noremap l l
noremap i k
noremap k j
noremap I 5k
noremap K 5j

noremap h i
noremap H I

map s <nop>
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>

syntax on
set mouse=a
set number
set norelativenumber
set cursorline
set wrap
set showcmd

set wildmenu
set hlsearch
exec "nohlsearch"
set incsearch
set ignorecase
set smartcase
noremap <LEADER><CR> :nohlsearch<CR>

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'connorholyday/vim-snazzy'

call plug#end()
color snazzy
let g:SnazzyTransparent = 1

